export const SUBMIT_BATCH = "SUBMIT_BATCH";
export const GET_BATCHES = "GET_BATCHES";
export const GET_PROGRAMS_TO_BE_OFFERED = "GET_PROGRAMS_TO_BE_OFFERED";
export const SUBMIT_OFFERED_PROGRAMS = "SUBMIT_OFFERED_PROGRAMS";
export const GET_OFFERED_PROGRAMS = "GET_OFFERED_PROGRAMS";
