export const GET_PREFERENCES_RECORD = "GET_PREFERENCES_RECORD";
export const GET_DEPARTMENT = "GET_DEPARTMENT";
export const GET_COURSES = "GET_COURSES";
export const SUBMIT_PREFERENCE = "SUBMIT_PREFERENCE";
export const DELETE_PREFERENCE = "DELETE_PREFERENCE";
