export const SELECTED_APPID = "SELECTED_APPID";
export const UNSELECT_APPID = "UNSELECT_APPID";
export const GET_APPLICATION_STATUS = "GET_APPLICATION_STATUS";
export const UPDATE_APPLICATION_STATUS = "UPDATE_APPLICATION_STATUS";
