export const GET_PROFILE_BY_ID = "GET_PROFILE_BY_ID";
export const UPDATE_PROFILE_DETAILS = "UPDATE_PROFILE_DETAILS";
export const UPDATE_PROFILE_PICTURE = "UPDATE_PROFILE_PICTURE";
export const UPDATE_COURSE_CATEGORY = "UPDATE_COURSE_CATEGORY";
