export const GET_ADMIN_DASHBOARD = "GET_ADMIN_DASHBOARD";
export const UPDATE_APPLICATION_STATUS_BY_ADMIN =
  "UPDATE_APPLICATION_STATUS_BY_ADMIN";
export const EMPTY_APPLICATION_FORM = "EMPTY_APPLICATION_FORM";
